version: '3.6'
services:
    web:
        depends_on:
            - mysql
        image: wordpress:latest
        links:
            - mysql
        environment:
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_HOST: mysql:3306
        ports:
            - 80:80
        working_dir: /var/www/html
        volumes:
            - ./wordpress:/var/www/html
        restart: always
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=wordpress
        volumes:
            - ./mysql:/var/lib/mysql
